#!/bin/sh
#set -x
. zbrewfuncs
setjavaenv

a2e() {
	orig=$1
	file=$(basename $1)
	out=${ZBREW_TMP}/$$.$file.ebcdic

	fromcp=`chtag -p ${orig} | awk '{ if ($2 == "untagged") { print "IBM-1047" } else { print $2; }}'`
	tocp='IBM-1047'
	
	iconv -f${fromcp} -t${tocp} <${orig} >${out}
	echo ${out}
	return $?
}

if [ $# -ne 1 ]; then
	echo "Expected exactly one parameter to be specified - the NTS directory" >&2
	exit 16
fi
NTS="$1"

mydir=$(callerdir ${0})
props="${mydir}/../../zbrew/properties/zbrewprops.json"
zbrewpropse zbrew config "${props}"

sysin=${ZBREW_TMP}/$$.gimzip.sysin
hlq="${ZBREW_HLQ}"
smpmcs="${hlq}ZHWZ110.MCS"
smpmcsptf1="${hlq}PTF.ZHW110.MCSPTF1"
smpmcsptf2="${hlq}PTF.ZHW110.MCSPTF2"
smphld="${hlq}ZHWZ110.HOLD"
smppdsf="${hlq}ZHWZ110.PDS"
smprelf="${hlq}ZHWZ110.F1"

echo "
<GIMZIP description=\"zbrew sample for testing\">
  <FILEDEF name=\"${smpmcs}\"
           description=\"mcs file\"
           archid=\"SMPMCS\"
           type=\"SMPPTFIN\">
  </FILEDEF>
  <FILEDEF name=\"${smpmcsptf1}\"
           description=\"mcs ptf1\"
           archid=\"SMPMCS.PTF1\"
           type=\"SMPPTFIN\">
  </FILEDEF>
  <FILEDEF name=\"${smphld}\"
           description=\"hold file\"
           archid=\"SMPHOLD\"
           type=\"SMPHOLD\">
  </FILEDEF>
  <FILEDEF name=\"${smprelf}\"
           description=\"hw file\"
           archid=\"F1\"
           type=\"SMPRELF\">
  </FILEDEF>
</GIMZIP>
" >${sysin}

drm -f "${smppdsf}" "${smprelf}" "${smpmcs}" "${smpmcsptf1}" "${smpmcsptf2}" "${smphld}"
dtouch -tpds "${smppdsf}"
dtouch -tpds "${smprelf}"
dtouch -tseq "${smpmcs}"
dtouch -tseq "${smpmcsptf1}"
dtouch -tseq "${smpmcsptf2}"
dtouch -tseq "${smphld}"

hfssmprelf=`a2e ${mydir}/smprelf/hw.rexx`
hfssmprelf1=`a2e ${mydir}/smprelf/hw1.rexx`
hfssmprelf2=`a2e ${mydir}/smprelf/hw2.rexx`
hfssmpmcs=`a2e ${mydir}/smpmcs/zhw110.mcs`
hfssmpmcsptf1=`a2e ${mydir}/smpmcs/zhw110ptf1.mcs`
hfssmpmcsptf2=`a2e ${mydir}/smpmcs/zhw110ptf2.mcs`
hfssmphld=`a2e ${mydir}/smphold/zhw110.hold`

dcp "${hfssmprelf}" "${smppdsf}(HW)"
dcp "${hfssmprelf1}" "${smppdsf}(HW1)"
dcp "${hfssmprelf2}" "${smppdsf}(HW2)"
out=`mvscmd --pgm=iebcopy --dd1=${smppdsf} --dd2=${smprelf} --sysprint=stdout --sysin=stdin <<zzz
  COPY INDD=DD1,OUTDD=DD2
zzz`
rc=$?
if [ $rc -gt 0 ]; then 
	echo "Unload of PDS ${smppdsf} failed." >&2
	echo "${out}" >&2
	exit 32
fi

dcp "${hfssmpmcs}" "${smpmcs}"
dcp "${hfssmpmcsptf1}" "${smpmcsptf1}"
dcp "${hfssmpmcsptf2}" "${smpmcsptf2}"
dcp "${hfssmphld}" "${smphld}"

sysut2=`mvstmp ${hlq}S2`
sysut3=`mvstmp ${hlq}S3`
sysut4=`mvstmp ${hlq}S4`
dtouch -tseq ${sysut2}
dtouch -tseq ${sysut3}
dtouch -tseq ${sysut4}

out=`mvscmdauth --pgm=gimzip --smpdir="${NTS}" --smpwkdir="${ZBREW_TMP}" --smpcpath="${SMPE_CLASSPATH}" --smpjhome="${SMPE_JAVAHOME}" --SYSUT2=${sysut2} --SYSUT3=${sysut3} --SYSUT4=${sysut4} --smpout=stdout --sysprint=stdout --sysin=${sysin}`
rc=$?

if [ $rc -gt 0 ]; then 
	echo "GIMZIP processing failed." >&2
	echo "${out}" >&2
	exit $rc
fi
rm ${hfssmprelf} ${hfssmprelf1} ${hfssmprelf2} ${hfssmpmcs} ${hfssmpmcsptf1} ${hfssmpmcsptf2} ${hfssmphld} ${sysin}
drm ${smppdsf} ${smprelf} ${smpmcs} ${smpmcsptf1} ${smphld} ${sysut2} ${sysut3} ${sysut4}

exit $rc
