#!/bin/sh
#set -x
. zbrewfuncs
setjavaenv

a2e() {
	orig=$1
	file=$(basename $1)
	out=${TMP}/$$.$file.ebcdic

	fromcp=`chtag -p ${orig} | awk '{ if ($2 == "untagged") { print "IBM-1047" } else { print $2; }}'`
	tocp='IBM-1047'
	
	iconv -f${fromcp} -t${tocp} <${orig} >${out}
	echo ${out}
	return $?
}

if [ $# -ne 1 ]; then
	echo "Expected exactly one parameter to be specified - the NTS directory" >&2
	exit 16
fi
NTS="$1"

mydir=$(callerdir ${0})
props="${mydir}/../../zbrew/properties/zbrew.properties"
. zbrewprops "${props}"
if [ $? -gt 0 ]; then
        echo "Internal Error. Unable to find ${props}" >&2
        exit 4
fi
sysin=${ZBREW_TMP}/$$.gimzip.sysin
hlq="ZHW"
smpmcs="${hlq}.ZHWZ110.MCS"
smphld="${hlq}.ZHWZ110.HOLD"
smppdsf="${hlq}.ZHWZ110.PDS"
smprelf="${hlq}.ZHWZ110.F1"

echo "
<GIMZIP description=\"zbrew sample for testing\">
  <FILEDEF name=\"${smpmcs}\"
           description=\"mcs file\"
           archid=\"SMPMCS\"
           type=\"SMPPTFIN\">
  </FILEDEF>
  <FILEDEF name=\"${smphld}\"
           description=\"hold file\"
           archid=\"SMPHOLD\"
           type=\"SMPHOLD\">
  </FILEDEF>
  <FILEDEF name=\"${smprelf}\"
           description=\"hw file\"
           archid=\"F1\"
           type=\"SMPRELF\">
  </FILEDEF>
</GIMZIP>
" >${sysin}

drm -f "${smprelf}" "${smpmcs}" "${smphld}"
dtouch -tpds "${smppdsf}"
dtouch -tseq "${smprelf}"
dtouch -tseq "${smpmcs}"
dtouch -tseq "${smphld}"

hfssmprelf=`a2e ${mydir}/smprelf/hw.rexx`
hfssmpmcs=`a2e ${mydir}/smpmcs/zhw110.mcs`
hfssmphld=`a2e ${mydir}/smphold/zhw110.hold`

dcp "${hfssmprelf}" "${smppdsf}(HW)"
out=`mvscmd --pgm=iebcopy --dd1=${smppdsf} --dd2=${smprelf} --sysprint=stdout --sysin=stdin <<zzz
  COPY INDD=DD1,OUTDD=DD2
zzz`
rc=$?
if [ $rc -gt 0 ]; then 
	echo "Unload of PDS ${smppdsf} failed." >&2
	echo "${out}" >&2
	exit 32
fi

dcp "${hfssmpmcs}" "${smpmcs}"
dcp "${hfssmphld}" "${smphld}"

sysut2=`mvstmp ${hlq}`
sysut3=`mvstmp ${hlq}`
sysut4=`mvstmp ${hlq}`
dtouch -tseq ${sysut2}
dtouch -tseq ${sysut3}
dtouch -tseq ${sysut4}

out=`mvscmdauth --pgm=gimzip --smpdir="${NTS}" --smpwkdir="${ZBREW_TMP}" --smpcpath="${SMPE_CLASSPATH}" --smpjhome="${SMPE_JAVAHOME}" --SYSUT2=${sysut2} --SYSUT3=${sysut3} --SYSUT4=${sysut4} --smpout=stdout --sysprint=stdout --sysin=${sysin}`
rc=$?

if [ $rc -gt 0 ]; then 
	echo "GIMZIP processing failed." >&2
	echo "${out}" >&2
	exit $rc
fi
rm ${hfssmprelf} ${hfssmpmcs} ${hfssmphld} ${sysin}
drm ${smppdsf} ${smprelf} ${smpmcs} ${smphld} ${sysut2} ${sysut3} ${sysut4}

exit $rc
